name: curlInterface
version: 2.0.0
date: 2018-08-27
description: |
    Simple Web Access

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Michael Torpey
      url: http://www-groups.mcs.st-andrews.ac.uk/~mct25/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Michael Torpey
      url: http://www-groups.mcs.st-andrews.ac.uk/~mct25/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/curlInterface/
readme: README.md
packageinfo: https://gap-packages.github.io/curlInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/curlInterface/releases/download/v2.0.0/curlInterface-2.0.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
