name: curlInterface
version: 2.2.3
date: 2022-08-15
description: |
    Simple Web Access

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Michael Young
      url: http://mct25.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Michael Young
      url: http://mct25.host.cs.st-andrews.ac.uk/

GAP: ">= 4.9"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/curlInterface/
readme: README.md
packageinfo: https://gap-packages.github.io/curlInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/curlInterface/releases/download/v2.2.3/curlInterface-2.2.3.tar.gz

abstract: |

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
